### ISSUE TITLE
Addons installation freezed because of database lock

### ISSUE THREAD

**Issue by cyrilgdn** [camptocamp/marabunta#11]
This bug happens if we run anthem commands in pre: in migrations.yml

Anthem will, on first command, create the database if not exists and install some base modules by starting an odoo in Context.
This odoo first creation will, inter alia, create the table ir_module_module.

After that, for addons installations setp, marabunta will perform a select on ir_module_module table ([in this method](https://github.com/camptocamp/marabunta/blob/master/marabunta/database.py#L153)) to list already installed module then will perform installations!

But, in case of a module installation try to alter ir_module_module table (e.g. :base_import_module which is installed by web_studio in V10 :)), the previous select will block this ALTER TABLE

**Comment by guewen** [comment]
@cyrilgdn what was your use case for using `anthem` in a `pre` step?

**Comment by cyrilgdn** [comment]
@guewen In all project (I think) we have a pre.py called by anthem for company setup for example.
