### ISSUE TITLE
[BUG] [1.7.0] all the migrations scripts are always launched from marabunta

### ISSUE THREAD

**Issue by leemannd** [camptocamp/marabunta#16]
To reproduce this issue:
- Launch a project from scratch without db. It passes all migrations steps.
- Stop the project
- Relaunch it => it will perform again all the creation steps.

Note: there is no 'marabunta_version' table created at the end of the migration.
as mentionned by @cyrilgdn, it seems to come from https://github.com/camptocamp/marabunta/pull/13/files . There is no 'conn.commit() at the end.

cc @guewen @yvaucher

**Comment by guewen** [comment]
Actually the block here: https://github.com/camptocamp/marabunta/pull/13/files#diff-3b85b3a99e1339c89fb9eeef16769a76R50 should commits at the end of the context manager, so the table should be there from the beginning.

Should be something else.

**Comment by guewen** [comment]
Forget what I just said, indeed the commit is missing on the connection.

**Comment by guewen** [comment]
Fixed in 0.6.1. Thanks!
