### ISSUE TITLE
[Question] Plans for marabunta?

### ISSUE THREAD

**Issue by blaggacao** [camptocamp/marabunta#19]
Hi Guewen
Hi Leonardo,
 @guewen @lepistone 

I am considering to use marabunta, but I see that it is 0.6.3 and that there has been little activity lately. Does it mean that there are plans or even possibilities to abandon this work?

**Comment by guewen** [comment]
Hi @blaggacao ,

We are using it actively in all our Odoo projects with github.com/camptocamp/docker-odoo-project
There is little activity because it works for our current needs :)

**Comment by blaggacao** [comment]
@guewen Ok, thanks, i hope beeing able to apport once implementing it. For us, we actually where planning something similar, also yaml based but desisted in favor of an "always base update" strategy. But I guess that's an opportunity to rethink and put some effort in migration scripting also on our end.

**Comment by blaggacao** [comment]
What are your thoughts of accepting eventually a `addons: rename` directive? In past refactorings I have learned that rename or merge operations on modules are always a two step transaction with traditional migration scripts. From an external spectator (marabunta) this could be made one single step. Would such attempt have a chance to be within the scope of marabunta, or would you argue that this would/should be part of a separate script?

**Comment by guewen** [comment]
I want marabunta to stay relatively agnostic (i.e. it should just run command lines, not include odoo scripting). I would say this should be done in `pre` / `post` operations by calling another script (we use mainly https://github.com/camptocamp/anthem but also direct calls to `psql` or other scripts).

**Comment by guewen** [comment]
> I want marabunta to stay relatively agnostic (i.e. it should just run command lines, not include odoo scripting).

That why for instance there is no `uninstall`, because there no command line option in odoo to do it.

**Comment by blaggacao** [comment]
Copy loud and clear 😉

**Comment by blaggacao** [comment]
I guess my last question: How would anthem compare to[ OdooRPC](https://github.com/osiell/odoorpc/tree/master/odoorpc)? Why  could I have an interest to use anthem over OdooRPC? Simplicity? The nice logging feature, you incorporated?

**Comment by guewen** [comment]
@blaggacao the big difference between them is that OdooRPC is using the RPC, when anthem imports odoo's API which is a huge avantage for:
* full access to the internal API, you can use private methods, run queries in the database, ...
* you can decide to rollback, savepoint, commit changes
* sometimes you can't login with RPC, but you can always use the Python API

Regarding your edit, yes we could say that :) Here's a very small example https://github.com/camptocamp/docker-odoo-project/tree/master/example/odoo/songs
