### ISSUE TITLE
Reminder for release 0.9.0

### ISSUE THREAD

**Issue by simahawk** [camptocamp/marabunta#34]
@guewen I made a [pre-release commit](https://github.com/camptocamp/marabunta/commit/1b1ec0c18f3b74ec8aed5d8deb62ceaab8712fd1) to be able to pin latest version in our builds.
We should amend it w/ proper changelog before doing the real release (which I cannot do :sob:).

**Comment by simahawk** [comment]
Internal issue https://github.com/camptocamp/odoo-template/issues/224

**Comment by guewen** [comment]
release 0.9.0 done https://github.com/camptocamp/marabunta/releases/tag/0.9.0
